# SCOPE OF THE PROJECT

The scope of this project is to use Artificial neural networks and deep learning to solve the churn rate of a bank.

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
churn_rate = pd.read_csv('Churn_Modelling.csv') #Reading the data

In [3]:
churn_rate.head() #Finding the first 5 rows

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
churn_rate.isnull().sum() #Checking for null values in Dataset

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
#looking through the data

x = churn_rate.iloc[:, 3: -1].values #Independent Variables
y = churn_rate.iloc[:, -1].values #Independent Variables

In [8]:
#Label encoding the "Gender" Column

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [9]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [13]:
#Using Hot Encoding to Encode the Geography column

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = ct.fit_transform(x)
print(x)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [16]:
#Splitting the data into Train and test Data

from sklearn.model_selection import train_test_split

x_train,x_test, y_train, y_test = train_test_split(x,y, test_size = 0.4, random_state =1)

In [18]:
#Feature scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)

x_test = sc.transform(x_test)

In [19]:
#Initialising the ANN

ANN = tf.keras.models.Sequential()

In [20]:
#Adding the Layers

ANN.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [21]:
#Adding the Second Layr
ANN.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [22]:
#Adding the output Layer

ANN.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [24]:
#Compiling The Layer

ANN.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'], )

In [25]:
ANN.fit(x_train, y_train, batch_size= 32, epochs = 100)

Epoch 1/100
188/188 [==============================] - 2s 1ms/step - loss: 0.5769 - accuracy: 0.7838
Epoch 2/100
188/188 [==============================] - 0s 1ms/step - loss: 0.4897 - accuracy: 0.8007
Epoch 3/100
188/188 [==============================] - 0s 1ms/step - loss: 0.4636 - accuracy: 0.8007
Epoch 4/100
188/188 [==============================] - 0s 1ms/step - loss: 0.4530 - accuracy: 0.8007
Epoch 5/100
188/188 [==============================] - 0s 1ms/step - loss: 0.4461 - accuracy: 0.8007
Epoch 6/100
188/188 [==============================] - 0s 1ms/step - loss: 0.4410 - accuracy: 0.8007
Epoch 7/100
188/188 [==============================] - 0s 1ms/step - loss: 0.4361 - accuracy: 0.8007
Epoch 8/100
188/188 [==============================] - 0s 2ms/step - loss: 0.4320 - accuracy: 0.8007
Epoch 9/100
188/188 [==============================] - 0s 1ms/step - loss: 0.4289 - accuracy: 0.8007
Epoch 10/100
188/188 [==============================] - 0s 1ms/step - loss: 0.4264 - accura

188/188 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8625
Epoch 82/100
188/188 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8637
Epoch 83/100
188/188 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8628
Epoch 84/100
188/188 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8632
Epoch 85/100
188/188 [==============================] - 0s 1ms/step - loss: 0.3321 - accuracy: 0.8620
Epoch 86/100
188/188 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8638
Epoch 87/100
188/188 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8620
Epoch 88/100
188/188 [==============================] - 0s 1ms/step - loss: 0.3321 - accuracy: 0.8638
Epoch 89/100
188/188 [==============================] - 0s 1ms/step - loss: 0.3324 - accuracy: 0.8632
Epoch 90/100
188/188 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 

In [28]:
#Predicting

print(ANN.predict(sc.transform([[1, 0, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [31]:
y_pred = ANN.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 1]]


In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3046  113]
 [ 449  392]]


0.8595